# Generated by Django 5.0.6 on 2024-07-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieStills',
            new_name='MovieStill',
        ),
    ]
